name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to OVH Harbor
      uses: docker/login-action@v1
      with:
        registry: 6410l998.c1.gra9.container-registry.ovh.net
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: 6410l998.c1.gra9.container-registry.ovh.net/unstoppable/unstoppable:latest
